const data = {
  "products": [
    { "id": 1, 
      "name": "Diamond Engagement Ring", 
      "material": "Diamond", 
      "product": "Ring", "price": 5000, "rating": 4.9, "wishlisted": true, "gender": "Women", "color": "Clear/White" },
    { "id": 2, "name": "Gold Cufflinks", "material": "Gold", "product": "Cufflinks", "price": 150, "rating": 4.7, "wishlisted": false, "gender": "Men", "color": "Black" },
    { "id": 3, "name": "Platinum Necklace", "material": "Platinum", "product": "Necklace", "price": 3000, "rating": 4.8, "wishlisted": true, "gender": "Women", "color": "Silver" },
    { "id": 4, "name": "Silver Chain", "material": "Silver", "product": "Chain", "price": 250, "rating": 4.5, "wishlisted": false, "gender": "Men", "color": "Gray" },
    { "id": 5, "name": "Emerald Pendant", "material": "Gemstones", "product": "Pendant", "price": 1200, "rating": 4.2, "wishlisted": true, "gender": "Women", "color": "Green" },
    { "id": 6, "name": "Gold Bracelet", "material": "Gold", "product": "Bracelet", "price": 800, "rating": 4.6, "wishlisted": false, "gender": "Women", "color": "Yellow" },
    { "id": 7, "name": "Diamond Earrings", "material": "Diamond", "product": "Earrings", "price": 2500, "rating": 5.0, "wishlisted": true, "gender": "Women", "color": "Clear/White" },
    { "id": 8, "name": "Silver Tie Clip", "material": "Silver", "product": "Tie Clip", "price": 100, "rating": 4.3, "wishlisted": true, "gender": "Men", "color": "Silver" },
    { "id": 9, "name": "Ruby Necklace", "material": "Gemstones", "product": "Necklace", "price": 1600, "rating": 4.4, "wishlisted": false, "gender": "Women", "color": "Red" },
    { "id": 10, "name": "Platinum Ring", "material": "Platinum", "product": "Ring", "price": 4000, "rating": 4.8, "wishlisted": true, "gender": "Men", "color": "Clear/White" },
    { "id": 11, "name": "Gold Cufflinks", "material": "Gold", "product": "Cufflinks", "price": 200, "rating": 4.6, "wishlisted": true, "gender": "Men", "color": "Brown" },
    { "id": 12, "name": "Silver Pendant", "material": "Silver", "product": "Pendant", "price": 700, "rating": 4.4, "wishlisted": false, "gender": "Women", "color": "Pink" },
    { "id": 13, "name": "Sapphire Earrings", "material": "Gemstones", "product": "Earrings", "price": 1400, "rating": 4.7, "wishlisted": true, "gender": "Women", "color": "Blue" },
    { "id": 14, "name": "Diamond Necklace", "material": "Diamond", "product": "Necklace", "price": 3200, "rating": 4.9, "wishlisted": false, "gender": "Women", "color": "Clear/White" },
    { "id": 15, "name": "Emerald Ring", "material": "Gemstones", "product": "Ring", "price": 2200, "rating": 4.8, "wishlisted": true, "gender": "Men", "color": "Green" },
    { "id": 16, "name": "Silver Earrings", "material": "Silver", "product": "Earrings", "price": 500, "rating": 4.5, "wishlisted": false, "gender": "Women", "color": "Gray" },
    { "id": 17, "name": "Diamond Cufflinks", "material": "Diamond", "product": "Cufflinks", "price": 1200, "rating": 4.9, "wishlisted": true, "gender": "Men", "color": "Clear/White" },
    { "id": 18, "name": "Gold Tie Clip", "material": "Gold", "product": "Tie Clip", "price": 120, "rating": 4.3, "wishlisted": false, "gender": "Men", "color": "Yellow" },
    { "id": 19, "name": "Platinum Pendant", "material": "Platinum", "product": "Pendant", "price": 2300, "rating": 4.7, "wishlisted": true, "gender": "Women", "color": "Clear/White" },
    { "id": 20, "name": "Silver Bracelet", "material": "Silver", "product": "Bracelet", "price": 600, "rating": 4.6, "wishlisted": false, "gender": "Men", "color": "Brown" },
    { "id": 21, "name": "Blue Sapphire Chain", "material": "Gemstones", "product": "Chain", "price": 1500, "rating": 4.5, "wishlisted": true, "gender": "Women", "color": "Blue" },
    { "id": 22, "name": "Gold Ring", "material": "Gold", "product": "Ring", "price": 1000, "rating": 4.8, "wishlisted": false, "gender": "Men", "color": "Yellow" },
    { "id": 23, "name": "Ruby Pendant", "material": "Gemstones", "product": "Pendant", "price": 1100, "rating": 4.3, "wishlisted": false, "gender": "Women", "color": "Red" },
    { "id": 24, "name": "Platinum Earrings", "material": "Platinum", "product": "Earrings", "price": 2800, "rating": 4.8, "wishlisted": true, "gender": "Women", "color": "Clear/White" },
    { "id": 25, "name": "Silver Chain", "material": "Silver", "product": "Chain", "price": 350, "rating": 4.6, "wishlisted": false, "gender": "Men", "color": "Gray" },
    { "id": 26, "name": "Emerald Earrings", "material": "Gemstones", "product": "Earrings", "price": 1500, "rating": 4.7, "wishlisted": true, "gender": "Women", "color": "Green" },
    { "id": 27, "name": "Gold Necklace", "material": "Gold", "product": "Necklace", "price": 2100, "rating": 4.9, "wishlisted": false, "gender": "Women", "color": "Yellow" },
    { "id": 28, "name": "Diamond Chain", "material": "Diamond", "product": "Chain", "price": 3800, "rating": 4.7, "wishlisted": true, "gender": "Men", "color": "Clear/White" },
    { "id": 29, "name": "Platinum Bracelet", "material": "Platinum", "product": "Bracelet", "price": 1500, "rating": 4.4, "wishlisted": false, "gender": "Women", "color": "Silver" },
    { "id": 30, "name": "Sapphire Ring", "material": "Gemstones", "product": "Ring", "price": 2000, "rating": 4.6, "wishlisted": true, "gender": "Men", "color": "Blue" },
    { "id": 31, "name": "Gold Pendant", "material": "Gold", "product": "Pendant", "price": 900, "rating": 4.8, "wishlisted": false, "gender": "Women", "color": "Yellow" },
    { "id": 32, "name": "Ruby Chain", "material": "Gemstones", "product": "Chain", "price": 1200, "rating": 4.5, "wishlisted": true, "gender": "Men", "color": "Red" },
    { "id": 33, "name": "Platinum Tie Clip", "material": "Platinum", "product": "Tie Clip", "price": 200, "rating": 4.7, "wishlisted": true, "gender": "Men", "color": "Silver" },
    { "id": 34, "name": "Silver Pendant", "material": "Silver", "product": "Pendant", "price": 600, "rating": 4.2, "wishlisted": false, "gender": "Men", "color": "Pink" },
    { "id": 35, "name": "Emerald Chain", "material": "Gemstones", "product": "Chain", "price": 1000, "rating": 4.6, "wishlisted": true, "gender": "Women", "color": "Green" },
    { "id": 36, "name": "Gold Earrings", "material": "Gold", "product": "Earrings", "price": 1300, "rating": 4.8, "wishlisted": true, "gender": "Men", "color": "Yellow" },
    { "id": 37, "name": "Diamond Tie Clip", "material": "Diamond", "product": "Tie Clip", "price": 500, "rating": 4.7, "wishlisted": false, "gender": "Men", "color": "Clear/White" },
    { "id": 38, "name": "Platinum Ring", "material": "Platinum", "product": "Ring", "price": 3200, "rating": 4.9, "wishlisted": true, "gender": "Men", "color": "Clear/White" },
    { "id": 39, "name": "Silver Cufflinks", "material": "Silver", "product": "Cufflinks", "price": 250, "rating": 4.3, "wishlisted": false, "gender": "Men", "color": "Gray" },
    { "id": 40, "name": "Sapphire Pendant", "material": "Gemstones", "product": "Pendant", "price": 900, "rating": 4.8, "wishlisted": true, "gender": "Women", "color": "Blue" },
    { "id": 41, "name": "Ruby Earrings", "material": "Gemstones", "product": "Earrings", "price": 1100, "rating": 4.4, "wishlisted": true, "gender": "Women", "color": "Red" },
    { "id": 42, "name": "Gold Chain", "material": "Gold", "product": "Chain", "price": 1400, "rating": 4.7, "wishlisted": false, "gender": "Men", "color": "Yellow" },
    { "id": 43, "name": "Diamond Pendant", "material": "Diamond", "product": "Pendant", "price": 1600, "rating": 4.6, "wishlisted": true, "gender": "Women", "color": "Clear/White" },
    { "id": 44, "name": "Platinum Chain", "material": "Platinum", "product": "Chain", "price": 2000, "rating": 4.5, "wishlisted": false, "gender": "Men", "color": "Silver" },
    { "id": 45, "name": "Silver Ring", "material": "Silver", "product": "Ring", "price": 500, "rating": 4.4, "wishlisted": true, "gender": "Women", "color": "Gray" },
    { "id": 46, "name": "Emerald Cufflinks", "material": "Gemstones", "product": "Cufflinks", "price": 1200, "rating": 4.6, "wishlisted": false, "gender": "Men", "color": "Green" },
    { "id": 47, "name": "Gold Pendant", "material": "Gold", "product": "Pendant", "price": 700, "rating": 4.5, "wishlisted": true, "gender": "Women", "color": "Yellow" },
    { "id": 48, "name": "Ruby Ring", "material": "Gemstones", "product": "Ring", "price": 1800, "rating": 4.6, "wishlisted": true, "gender": "Men", "color": "Red" },
    { "id": 49, "name": "Platinum Earrings", "material": "Platinum", "product": "Earrings", "price": 2200, "rating": 4.9, "wishlisted": false, "gender": "Women", "color": "Clear/White" },
    { "id": 50, "name": "Silver Chain", "material": "Silver", "product": "Chain", "price": 700, "rating": 4.3, "wishlisted": true, "gender": "Men", "color": "Gray" }
  ]
}


export default data;