const data = {
  "products": [
    {
      "id": 1,
      "name": "Gold Necklace",
      "material": "Gold",
      "product": "Necklace",
      "price": 1500.00,
      "rating": 4.5,
      "wishlisted": true,
      "gender": "Women",
      "color": "Yellow"
    },
    {
      "id": 2,
      "name": "Silver Ring",
      "material": "Silver",
      "product": "Ring",
      "price": 500.00,
      "rating": 4.0,
      "wishlisted": false,
      "gender": "Men",
      "color": "Silver"
    },
    {
      "id": 3,
      "name": "Diamond Earrings",
      "material": "Diamond",
      "product": "Earrings",
      "price": 2500.00,
      "rating": 4.8,
      "wishlisted": true,
      "gender": "Women",
      "color": "White"
    },
    {
      "id": 4,
      "name": "Gemstone Bracelet",
      "material": "Gems",
      "product": "Bracelet",
      "price": 1200.00,
      "rating": 4.2,
      "wishlisted": false,
      "gender": "Women",
      "color": "Blue"
    },
    {
      "id": 5,
      "name": "Gold Ring",
      "material": "Gold",
      "product": "Ring",
      "price": 1800.00,
      "rating": 4.7,
      "wishlisted": true,
      "gender": "Men",
      "color": "Yellow"
    },
    {
      "id": 6,
      "name": "Silver Bracelet",
      "material": "Silver",
      "product": "Bracelet",
      "price": 700.00,
      "rating": 4.1,
      "wishlisted": false,
      "gender": "Women",
      "color": "Silver"
    },
    {
      "id": 7,
      "name": "Gold Earrings",
      "material": "Gold",
      "product": "Earrings",
      "price": 1350.00,
      "rating": 4.6,
      "wishlisted": true,
      "gender": "Women",
      "color": "Yellow"
    },
    {
      "id": 8,
      "name": "Diamond Ring",
      "material": "Diamond",
      "product": "Ring",
      "price": 3500.00,
      "rating": 4.9,
      "wishlisted": true,
      "gender": "Men",
      "color": "White"
    },
    {
      "id": 9,
      "name": "Gemstone Necklace",
      "material": "Gems",
      "product": "Necklace",
      "price": 2200.00,
      "rating": 4.3,
      "wishlisted": false,
      "gender": "Women",
      "color": "Green"
    },
    {
      "id": 10,
      "name": "Silver Earrings",
      "material": "Silver",
      "product": "Earrings",
      "price": 650.00,
      "rating": 3.9,
      "wishlisted": false,
      "gender": "Women",
      "color": "Silver"
    },
    {
      "id": 11,
      "name": "Gold Bracelet",
      "material": "Gold",
      "product": "Bracelet",
      "price": 1600.00,
      "rating": 4.4,
      "wishlisted": true,
      "gender": "Women",
      "color": "Yellow"
    },
    {
      "id": 12,
      "name": "Diamond Bracelet",
      "material": "Diamond",
      "product": "Bracelet",
      "price": 4000.00,
      "rating": 4.7,
      "wishlisted": true,
      "gender": "Men",
      "color": "White"
    },
    {
      "id": 13,
      "name": "Silver Necklace",
      "material": "Silver",
      "product": "Necklace",
      "price": 900.00,
      "rating": 4.2,
      "wishlisted": false,
      "gender": "Women",
      "color": "Silver"
    },
    {
      "id": 14,
      "name": "Gold Anklet",
      "material": "Gold",
      "product": "Anklet",
      "price": 1450.00,
      "rating": 4.3,
      "wishlisted": true,
      "gender": "Women",
      "color": "Yellow"
    },
    {
      "id": 15,
      "name": "Gemstone Earrings",
      "material": "Gems",
      "product": "Earrings",
      "price": 1100.00,
      "rating": 4.4,
      "wishlisted": true,
      "gender": "Women",
      "color": "Purple"
    },
    {
      "id": 16,
      "name": "Diamond Necklace",
      "material": "Diamond",
      "product": "Necklace",
      "price": 4500.00,
      "rating": 4.9,
      "wishlisted": true,
      "gender": "Women",
      "color": "White"
    },
    {
      "id": 17,
      "name": "Silver Anklet",
      "material": "Silver",
      "product": "Anklet",
      "price": 500.00,
      "rating": 3.8,
      "wishlisted": false,
      "gender": "Women",
      "color": "Silver"
    },
    {
      "id": 18,
      "name": "Gold Brooch",
      "material": "Gold",
      "product": "Brooch",
      "price": 1300.00,
      "rating": 4.5,
      "wishlisted": true,
      "gender": "Men",
      "color": "Yellow"
    },
    {
      "id": 19,
      "name": "Gemstone Ring",
      "material": "Gems",
      "product": "Ring",
      "price": 950.00,
      "rating": 4.0,
      "wishlisted": false,
      "gender": "Men",
      "color": "Red"
    },
    {
      "id": 20,
      "name": "Diamond Brooch",
      "material": "Diamond",
      "product": "Brooch",
      "price": 5000.00,
      "rating": 4.8,
      "wishlisted": true,
      "gender": "Men",
      "color": "White"
    },
    {
      "id": 21,
      "name": "Silver Brooch",
      "material": "Silver",
      "product": "Brooch",
      "price": 600.00,
      "rating": 3.9,
      "wishlisted": false,
      "gender": "Men",
      "color": "Silver"
    },
    {
      "id": 22,
      "name": "Gold Pendant",
      "material": "Gold",
      "product": "Pendant",
      "price": 1200.00,
      "rating": 4.2,
      "wishlisted": true,
      "gender": "Men",
      "color": "Yellow"
    },
    {
      "id": 23,
      "name": "Gemstone Pendant",
      "material": "Gems",
      "product": "Pendant",
      "price": 1050.00,
      "rating": 4.3,
      "wishlisted": false,
      "gender": "Women",
      "color": "Green"
    },
    {
      "id": 24,
      "name": "Diamond Anklet",
      "material": "Diamond",
      "product": "Anklet",
      "price": 5500.00,
      "rating": 4.7,
      "wishlisted": true,
      "gender": "Women",
      "color": "White"
    },
    {
      "id": 25,
      "name": "Silver Pendant",
      "material": "Silver",
      "product": "Pendant",
      "price": 700.00,
      "rating": 4.1,
      "wishlisted": false,
      "gender": "Men",
      "color": "Silver"
    },
    {
      "id": 26,
      "name": "Elegant Gold Necklace",
      "material": "Gold",
      "product": "Necklace",
      "price": 1500,
      "rating": 4.8,
      "wishlisted": true,
      "gender": "Women",
      "color": "Yellow"
    },
    {
      "id": 27,
      "name": "Classic Silver Ring",
      "material": "Silver",
      "product": "Ring",
      "price": 300,
      "rating": 4.0,
      "wishlisted": false,
      "gender": "Men",
      "color": "Silver"
    },
    {
      "id": 28,
      "name": "Ruby Gemstone Pendant",
      "material": "Gems",
      "product": "Pendant",
      "price": 800,
      "rating": 4.5,
      "wishlisted": true,
      "gender": "Women",
      "color": "Red"
    },
    {
      "id": 29,
      "name": "Pearl Stud Earrings",
      "material": "Pearl",
      "product": "Earrings",
      "price": 1200,
      "rating": 4.2,
      "wishlisted": false,
      "gender": "Women",
      "color": "White"
    },
    {
      "id": 30,
      "name": "Sapphire Bracelet",
      "material": "Gems",
      "product": "Bracelet",
      "price": 2500,
      "rating": 4.6,
      "wishlisted": true,
      "gender": "Women",
      "color": "Blue"
    },
    {
      "id": 31,
      "name": "Platinum Wedding Band",
      "material": "Platinum",
      "product": "Ring",
      "price": 3000,
      "rating": 4.9,
      "wishlisted": true,
      "gender": "Men",
      "color": "Silver"
    },
    {
      "id": 32,
      "name": "Onyx Beaded Necklace",
      "material": "Onyx",
      "product": "Necklace",
      "price": 1100,
      "rating": 4.1,
      "wishlisted": false,
      "gender": "Women",
      "color": "Black"
    },
    {
      "id": 33,
      "name": "Turquoise Gemstone Anklet",
      "material": "Gems",
      "product": "Anklet",
      "price": 950,
      "rating": 4.3,
      "wishlisted": true,
      "gender": "Women",
      "color": "Blue"
    },
    {
      "id": 34,
      "name": "Rose Gold Engagement Ring",
      "material": "Gold",
      "product": "Ring",
      "price": 3500,
      "rating": 4.9,
      "wishlisted": true,
      "gender": "Women",
      "color": "Rose Gold"
    },
    {
      "id": 35,
      "name": "Sterling Silver Cufflinks",
      "material": "Silver",
      "product": "Cufflinks",
      "price": 450,
      "rating": 4.0,
      "wishlisted": false,
      "gender": "Men",
      "color": "Silver"
    },
    {
      "id": 36,
      "name": "Emerald Stud Earrings",
      "material": "Gems",
      "product": "Earrings",
      "price": 1400,
      "rating": 4.5,
      "wishlisted": true,
      "gender": "Women",
      "color": "Green"
    },
    {
      "id": 37,
      "name": "Bronze Choker Necklace",
      "material": "Bronze",
      "product": "Necklace",
      "price": 700,
      "rating": 3.8,
      "wishlisted": false,
      "gender": "Women",
      "color": "Bronze"
    },
    {
      "id": 38,
      "name": "Amethyst Bracelet",
      "material": "Gems",
      "product": "Bracelet",
      "price": 1800,
      "rating": 4.4,
      "wishlisted": true,
      "gender": "Women",
      "color": "Purple"
    },
    {
      "id": 39,
      "name": "Titanium Band Ring",
      "material": "Titanium",
      "product": "Ring",
      "price": 2000,
      "rating": 4.6,
      "wishlisted": false,
      "gender": "Men",
      "color": "Silver"
    },
    {
      "id": 40,
      "name": "Aquamarine Pendant",
      "material": "Gems",
      "product": "Pendant",
      "price": 1600,
      "rating": 4.7,
      "wishlisted": true,
      "gender": "Women",
      "color": "Blue"
    },
    {
      "id": 41,
      "name": "Coral Anklet",
      "material": "Gems",
      "product": "Anklet",
      "price": 800,
      "rating": 4.2,
      "wishlisted": false,
      "gender": "Women",
      "color": "Red"
    },
    {
      "id": 42,
      "name": "Palladium Necklace",
      "material": "Palladium",
      "product": "Necklace",
      "price": 3100,
      "rating": 4.8,
      "wishlisted": true,
      "gender": "Men",
      "color": "Silver"
    },
    {
      "id": 43,
      "name": "Citrine Earrings",
      "material": "Gems",
      "product": "Earrings",
      "price": 1150,
      "rating": 4.4,
      "wishlisted": true,
      "gender": "Women",
      "color": "Yellow"
    },
    {
      "id": 44,
      "name": "Ivory Brooch",
      "material": "Ivory",
      "product": "Brooch",
      "price": 4500,
      "rating": 4.9,
      "wishlisted": true,
      "gender": "Men",
      "color": "White"
    },
    {
      "id": 45,
      "name": "Sapphire Brooch",
      "material": "Gems",
      "product": "Brooch",
      "price": 3600,
      "rating": 4.7,
      "wishlisted": true,
      "gender": "Men",
      "color": "Blue"
    },
    {
      "id": 46,
      "name": "Gold Stud Earrings",
      "material": "Gold",
      "product": "Earrings",
      "price": 1250,
      "rating": 4.5,
      "wishlisted": true,
      "gender": "Women",
      "color": "Yellow"
    },
    {
      "id": 47,
      "name": "Black Onyx Ring",
      "material": "Onyx",
      "product": "Ring",
      "price": 900,
      "rating": 4.2,
      "wishlisted": false,
      "gender": "Men",
      "color": "Black"
    },
    {
      "id": 48,
      "name": "Peridot Necklace",
      "material": "Gems",
      "product": "Necklace",
      "price": 1800,
      "rating": 4.5,
      "wishlisted": true,
      "gender": "Women",
      "color": "Green"
    },
    {
      "id": 49,
      "name": "Rose Gold Cufflinks",
      "material": "Gold",
      "product": "Cufflinks",
      "price": 1400,
      "rating": 4.3,
      "wishlisted": true,
      "gender": "Men",
      "color": "Rose Gold"
    },
    {
      "id": 50,
      "name": "Turquoise Stud Earrings",
      "material": "Gems",
      "product": "Earrings",
      "price": 850,
      "rating": 4.1,
      "wishlisted": false,
      "gender": "Women",
      "color": "Blue"
    }
  ]
};

export default data;